[build.environment]
HUGO_VERSION = "0.134.2"
BULMA_SASS_VERSION = "1.02.5"

[build]
publish = "public"
command = """\
  curl -LJO https://github.com/jgthms/bulma/archive/refs/tags/${BULMA_SASS_VERSION}.tar.gz && \
  tar -xf ${BULMA_SASS_VERSION}.tar.gz && \
  rm ${BULMA_SASS_VERSION}.tar.gz && \
  export PATH=/opt/build/repo/bulma:$PATH && \
  hugo --gc --minify \
  """