[build.environment]
HUGO_VERSION = "0.134.2"
BULMA_SASS_VERSION = "1.0.2"

[build]
publish = "public"
command = """\
  curl -LJO https://github.com/jgthms/bulma/archive/refs/tags/${BULMA_SASS_VERSION}.tar.gz && \
  tar -xf bulma-1.0.2.tar.gz && \
  rm bulma-1.0.2.tar.gz && \
  export PATH=/opt/build/repo/bulma:$PATH && \
  hugo --gc --minify \
  """